name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t auth-microservices:1.0.0 .

    - name: Tag Docker image
      run: docker tag user-microservices:1.0.0 "${{ secrets.DOCKER_USERNAME }}/user-microservices:1.0.0"

    - name: Push Docker image
      run: docker push "${{ secrets.DOCKER_USERNAME }}/user-microservices:1.0.0"

    - name: Clean up temporary files
      run: |
        # Remove temporary Docker image
        docker rmi user-microservices:1.0.0

        # Remove Docker image tag
        docker rmi "${{ secrets.DOCKER_USERNAME }}/user-microservices:1.0.0"
